local LSM = LibStub("LibSharedMedia-3.0") 

LSM:Register("font", "ElvUI A", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI A.ttf]]) 
LSM:Register("font", "ElvUI B", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI B.ttf]]) 
LSM:Register("font", "ElvUI C", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI C.ttf]]) 
LSM:Register("font", "ElvUI D", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI D.ttf]]) 
LSM:Register("font", "ElvUI E", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI E.ttf]]) 
LSM:Register("font", "ElvUI F", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI F.ttf]]) 
LSM:Register("font", "ElvUI G", [[Interface\Addons\ElvUI_CustomMedia\Fonts\ElvUI G.ttf]]) 


LSM:Register("statusbar", "ElvUI A", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI A.tga]]) 
LSM:Register("statusbar", "ElvUI B", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI B.tga]]) 
LSM:Register("statusbar", "ElvUI C", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI C.tga]]) 
LSM:Register("statusbar", "ElvUI D", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI D.tga]]) 
LSM:Register("statusbar", "ElvUI E", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI E.tga]]) 
LSM:Register("statusbar", "ElvUI F", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI F.tga]]) 
LSM:Register("statusbar", "ElvUI G", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI G.tga]]) 
LSM:Register("statusbar", "ElvUI H", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI H.tga]]) 
LSM:Register("statusbar", "ElvUI I", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI I.tga]]) 
LSM:Register("statusbar", "ElvUI J", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI J.tga]]) 
LSM:Register("statusbar", "ElvUI K", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI K.tga]]) 
LSM:Register("statusbar", "ElvUI L", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI L.tga]]) 
LSM:Register("statusbar", "ElvUI M", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI M.tga]]) 
LSM:Register("statusbar", "ElvUI N", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI N.tga]]) 
LSM:Register("statusbar", "ElvUI O", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI O.tga]]) 
LSM:Register("statusbar", "ElvUI P", [[Interface\Addons\ElvUI_CustomMedia\Statusbar\ElvUI P.tga]]) 
